# Generated by Django 4.2.6 on 2023-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, default='media/body.png', null=True, upload_to='media'),
        ),
    ]
