# Generated by Django 4.2.6 on 2023-10-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_note_picture_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AddField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, default='media/dog.png', null=True, upload_to='media'),
        ),
    ]
