# Generated by Django 4.2.6 on 2023-10-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='picture',
            field=models.ImageField(blank=True, default='media/dog.png', null=True, upload_to='media'),
        ),
    ]
